name: "BT HCI Proxy arm"
version: "0.1.1"
slug: "bt-hci-proxy-arm"
description: "Attaches a Bluetooth HCI UART device (btattach) for use with the bt-proxy host-side service"
url: "https://github.com/tianq02/homeassistant-bt-proxy-arm"
arch:
  - amd64
  - aarch64
startup: system
boot: auto
init: false
uart: true
privileged:
  - SYS_MODULE
  - NET_ADMIN
host_dbus: true
options:
  device: "/dev/ttyS1"
  protocol: "h4"
  passive_scan: true
  adapter_name_prefix: "BT Proxy for"
schema:
  device: "device(subsystem=tty)"
  protocol: str
  passive_scan: bool
  adapter_name_prefix: str?
